language: python
sudo: false
python:
  - "pypy"
  - "pypy3"
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
install:
  - pip install -U pytest
  - travis_retry pip install coverage
  - pip install coveralls
  - pip install pytest-cov
  - python setup.py develop
script:
  py.test -v --cov tinydb_smartcache
after_success:
  coveralls
